# Generated by patternizer
# This Makefile includes the common pattern targets from Makefile-common
# You can add custom targets above or below the include line

include Makefile-common

##@ Sleeping Through Disasters

CLUSTERGROUP_LABEL ?= active
.PHONY: import-active
import-active: ## Import the active site into ACM as clusterGroup=active (set VP_SPOKECONFIG and VP_HUBCONFIG)
	@$(ANSIBLE_RUN) -e clustergroup_label=$(CLUSTERGROUP_LABEL) rhvp.cluster_utils.import_spoke_cluster

.PHONY: validate-dr
validate-dr: ## Render every chart with its full values stack and check the DR invariants (needs helm)
	@rm -rf .dr-render && tests/dr/render.sh .dr-render >/dev/null && python3 tests/dr/invariants.py .dr-render; rc=$$?; rm -rf .dr-render; exit $$rc
