apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - operators-both.yaml
  - namespace-both.yaml
  - postgres-active.yaml
  - postgres-passive.yaml
  - skupper-active.yaml
  - skupper-passive.yaml
  - suitecrm-active.yaml
  - suitecrm-passive.yaml
  - volsync-active.yaml
  - volsync-passive.yaml
