---
# Creates the odoo namespace on both clusters along with any
# RBAC and base resources both clusters need.
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: odoo-namespace
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: odoo-dr
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: odoo-both
        requeueAfterSeconds: 180
  template:
    metadata:
      name: 'odoo-namespace-{{.name}}'
      labels:
        app.kubernetes.io/part-of: odoo-dr
    spec:
      project: default
      source:
        repoURL: https://github.com/ryannix123/acm-odoo.git
        targetRevision: main
        path: clusters/both/namespace
      destination:
        name: '{{.name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
